# This file ensures your code is up todate and travis uses it
# to push you lib to the master branch of our repo in Pypi
# This code runs automatically to build the library
language: python
python:
  - 3.9

# update pip to the latest version
before_install:
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
  - python -m pytest -vv

deploy:
  provider: pypi
